theme: hugo-developer-portfolio
baseURL: https://example.com
languageCode: en-gb
title: Sam Robbins
googleAnalytics: ''
module:
  imports:
    - path: github.com/samrobbins85/hugo-developer-portfolio
params:
  author: Sam Robbins
  contact:
    enable: yes
    formAction: ''
  description: The website of Sam Robbins, 2nd Year Computer Science Student at Durham
    University
  footer:
    address: Durham, UK
    email: samrobbinsgb@gmail.com
    googlemaps: https://www.google.com/maps/embed/v1/place?q=place_id:ChIJwbHYJaUqfEgRK0Ui9dVGimc&key=AIzaSyAE_4rVAKux_DSPcb_OdSRDaovtPOSk_3U
  home: Home
  plugins:
    css:
      - URL: https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css
    js:
      - URL: https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js
      - URL: https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js
menu:
  main:
    - URL: about
      name: About
      weight: 1
    - URL: blog
      name: Blog
      weight: 2
    - URL: portfolio
      name: Portfolio
      weight: 3
    - URL: contact
      name: Contact
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: yes
    style: rainbow_dash
    tabWidth: 4
